/* =======================================================================
   AFFILIATE LINKS — now cloaked via redirects in vercel.json
   -----------------------------------------------------------------------
   Every affiliate button points to a clean /go/<product> path on your own
   domain. Vercel redirects each /go/<product> to your real SpringWell
   (Everflow) tracking link. The raw affiliate URLs never appear in the
   page source.

   TO CHANGE OR ADD A LINK: edit the "redirects" list in /vercel.json
   (or the LINKS map in build.py and re-run it). You do NOT edit this file.

   This script only enforces that every affiliate link stays compliant
   (rel="sponsored nofollow noopener", opens in a new tab) per Google's
   guidelines — keep it.
   ======================================================================= */
(function () {
  document.addEventListener("DOMContentLoaded", function () {
    document.querySelectorAll('a[data-aff]').forEach(function (a) {
      a.setAttribute("rel", "sponsored nofollow noopener");
      a.setAttribute("target", "_blank");
    });
  });
})();
